import {
  Archive,
  BadgeIndianRupee,
  Eraser,
  FileImage,
  FileSpreadsheet,
  FileText,
  Images,
  Layers,
  Minimize2,
  PackageCheck,
  ScanText,
  SplitSquareHorizontal,
} from 'lucide-react';
import type { ToolDefinition } from '../types/tools';

const onePdf = {
  maxFiles: 1,
  acceptedTypes: ['application/pdf'],
  errorMessage: 'Please upload a single PDF file.',
};

export const tools: ToolDefinition[] = [
  {
    id: 'pdf-to-word',
    title: 'PDF to Word',
    slug: '/pdf-to-word',
    category: 'PDF Tools',
    description: 'Convert PDF files into editable DOCX documents with layout-aware extraction.',
    inputFormats: ['PDF'],
    outputFormats: ['DOCX'],
    icon: FileText,
    status: 'coming-soon',
    uploadRule: onePdf,
    related: ['ocr-pdf', 'pdf-to-excel', 'compress-pdf'],
    seoTitle: 'PDF to Word Converter - DocBit',
  },
  {
    id: 'word-to-pdf',
    title: 'Word to PDF',
    slug: '/word-to-pdf',
    category: 'Document Tools',
    description: 'Create business-ready PDFs from DOC and DOCX files.',
    inputFormats: ['DOC', 'DOCX'],
    outputFormats: ['PDF'],
    icon: FileText,
    status: 'coming-soon',
    uploadRule: { maxFiles: 1, acceptedTypes: ['application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'], errorMessage: 'Please upload a single Word document.' },
    related: ['pdf-to-word', 'compress-pdf', 'image-to-pdf'],
    seoTitle: 'Word to PDF Converter - DocBit',
  },
  {
    id: 'merge-pdf',
    title: 'Merge PDF',
    slug: '/merge-pdf',
    category: 'PDF Tools',
    description: 'Combine up to 50 PDFs into one organized document.',
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    icon: Layers,
    status: 'available',
    uploadRule: { maxFiles: 50, acceptedTypes: ['application/pdf'], errorMessage: 'Maximum 50 PDF files allowed for merging.' },
    related: ['split-pdf', 'compress-pdf', 'pdf-to-word'],
    seoTitle: 'Merge PDF Online - DocBit',
  },
  {
    id: 'compress-pdf',
    title: 'Compress PDF',
    slug: '/compress-pdf',
    category: 'PDF Tools',
    description: 'Reduce PDF size with real-time progress and privacy-first temporary processing.',
    inputFormats: ['PDF'],
    outputFormats: ['PDF'],
    icon: Minimize2,
    status: 'available',
    uploadRule: onePdf,
    related: ['merge-pdf', 'pdf-to-word', 'image-to-pdf'],
    seoTitle: 'Compress PDF Online - DocBit',
  },
  {
    id: 'image-to-pdf',
    title: 'Image to PDF',
    slug: '/image-to-pdf',
    category: 'Image Tools',
    description: 'Convert up to 50 images into a clean, ordered PDF.',
    inputFormats: ['JPG', 'PNG', 'WEBP', 'HEIC'],
    outputFormats: ['PDF'],
    icon: Images,
    status: 'available',
    uploadRule: { maxFiles: 50, acceptedTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/heic'], errorMessage: 'Maximum 50 images allowed per conversion.' },
    related: ['pdf-to-image', 'compress-pdf', 'merge-pdf'],
    seoTitle: 'Image to PDF Converter - DocBit',
  },
  {
    id: 'pdf-to-excel',
    title: 'PDF to Excel',
    slug: '/pdf-to-excel',
    category: 'Excel Tools',
    description: 'Extract tables from PDFs into structured spreadsheets.',
    inputFormats: ['PDF'],
    outputFormats: ['XLSX'],
    icon: FileSpreadsheet,
    status: 'coming-soon',
    uploadRule: onePdf,
    related: ['invoice-to-excel', 'ocr-pdf', 'pdf-to-word'],
    seoTitle: 'PDF to Excel Converter - DocBit',
  },
  {
    id: 'invoice-to-excel',
    title: 'Invoice PDF to Excel',
    slug: '/invoice-to-excel',
    category: 'Excel Tools',
    description: 'Turn invoice PDFs into reviewable Excel rows for finance workflows.',
    inputFormats: ['PDF'],
    outputFormats: ['XLSX', 'CSV'],
    icon: BadgeIndianRupee,
    status: 'coming-soon',
    uploadRule: onePdf,
    related: ['pdf-to-excel', 'ocr-pdf', 'compress-pdf'],
    seoTitle: 'Invoice PDF to Excel - DocBit',
  },
  {
    id: 'image-background-remover',
    title: 'Image Background Remover',
    slug: '/image-background-remover',
    category: 'Image Tools',
    description: 'Create transparent PNG product and profile images.',
    inputFormats: ['JPG', 'PNG', 'WEBP'],
    outputFormats: ['PNG'],
    icon: Eraser,
    status: 'coming-soon',
    uploadRule: { maxFiles: 1, acceptedTypes: ['image/jpeg', 'image/png', 'image/webp'], errorMessage: 'Please upload one image at a time.' },
    related: ['image-to-product-listing', 'image-to-pdf', 'compress-pdf'],
    seoTitle: 'Image Background Remover - DocBit',
  },
  {
    id: 'image-to-product-listing',
    title: 'Image to Product Listing',
    slug: '/image-to-product-listing',
    category: 'Image Tools',
    description: 'Prepare product photos and structured listing assets for marketplaces.',
    inputFormats: ['JPG', 'PNG', 'WEBP'],
    outputFormats: ['ZIP', 'CSV'],
    icon: PackageCheck,
    status: 'coming-soon',
    uploadRule: { maxFiles: 12, acceptedTypes: ['image/jpeg', 'image/png', 'image/webp'], errorMessage: 'Please upload up to 12 product images.' },
    related: ['image-background-remover', 'image-to-pdf', 'pdf-to-excel'],
    seoTitle: 'Image to Product Listing - DocBit',
  },
  {
    id: 'ocr-pdf', title: 'OCR PDF', slug: '/ocr-pdf', category: 'PDF Tools', description: 'Make scanned PDFs searchable and selectable.', inputFormats: ['PDF'], outputFormats: ['Searchable PDF', 'TXT'], icon: ScanText, status: 'coming-soon', uploadRule: onePdf, related: ['pdf-to-word', 'pdf-to-excel', 'compress-pdf'], seoTitle: 'OCR PDF Online - DocBit'
  },
  {
    id: 'split-pdf', title: 'Split PDF', slug: '/split-pdf', category: 'PDF Tools', description: 'Extract ranges or split each page into separate files.', inputFormats: ['PDF'], outputFormats: ['PDF'], icon: SplitSquareHorizontal, status: 'available', uploadRule: onePdf, related: ['merge-pdf', 'compress-pdf', 'pdf-to-image'], seoTitle: 'Split PDF Online - DocBit'
  },
  {
    id: 'pdf-to-image', title: 'PDF to Image', slug: '/pdf-to-image', category: 'PDF Tools', description: 'Export PDF pages as high-quality images.', inputFormats: ['PDF'], outputFormats: ['PNG', 'JPG'], icon: FileImage, status: 'coming-soon', uploadRule: { maxFiles: 1, acceptedTypes: ['application/pdf'], errorMessage: 'Only one PDF can be converted at a time.' }, related: ['image-to-pdf', 'split-pdf', 'compress-pdf'], seoTitle: 'PDF to Image Converter - DocBit'
  },
  {
    id: 'pdf-to-grayscale', title: 'PDF to Grayscale', slug: '/pdf-to-grayscale', category: 'PDF Tools', description: 'Convert PDF pages to grayscale for print-ready files.', inputFormats: ['PDF'], outputFormats: ['PDF'], icon: Archive, status: 'coming-soon', uploadRule: onePdf, related: ['compress-pdf', 'merge-pdf', 'split-pdf'], seoTitle: 'PDF to Grayscale - DocBit'
  },
];

export const categories = ['PDF Tools', 'Image Tools', 'Document Tools', 'Excel Tools', 'PowerPoint Tools', 'SVG Tools'] as const;
export const popularTools = tools.filter((tool) => ['pdf-to-word', 'merge-pdf', 'compress-pdf', 'image-to-pdf', 'pdf-to-excel', 'ocr-pdf', 'invoice-to-excel', 'image-background-remover', 'image-to-product-listing'].includes(tool.id));
